export const INPUT_LOGIN_EMAIL = 'INPUT_LOGIN_EMAIL';
export const INPUT_LOGIN_PASSWORD = 'INPUT_LOGIN_PASSWORD';
export const INPUT_SIGNUP_EMAIL = 'INPUT_SIGNUP_EMAIL';
export const INPUT_SIGNUP_PASSWORD = 'INPUT_SIGNUP_PASSWORD';
export const INPUT_SIGNUP_REPEAT_PASSWORD = 'INPUT_SIGNUP_REPEAT_PASSWORD';
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM';
export const RESET_SIGNUP_FORM = 'RESET_SIGNUP_FORM';